apiVersion: v1
kind: Service
metadata:
    name: "smk8scluster3-80b1"
    labels:
        app: "smk8scluster3-80b1"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "smk8scluster3-80b1"