apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: oidc-policy
spec:
  oidc:
    clientID: 0oa2o1eskh3FnX8XZ5d7
    clientSecret: oidc-secret
    authEndpoint: https://dev-76512594.okta.com/oauth2/v1/authorize
    tokenEndpoint: https://dev-76512594.okta.com/oauth2/v1/token
    jwksURI: https://dev-76512594.okta.com/oauth2/v1/keys